### ISSUE TITLE
[Dev branch] Appearance disclaimer is squished and extends beyond bounds

### ISSUE THREAD

**Issue by Ellpeck** [catppuccin/obsidian#102]
This started happening a while back, presumably with an Obsidian update that changed the internal layouting of the settings menu somehow. The disclaimer about using the style settings plugin is now very squished and extends far beyond the bounds of the actual setting:

![image](https://github.com/user-attachments/assets/a34266f2-cdb0-4e49-b4d6-f9084724221d)

I'm really loving the development version of the theme - it feels a lot more streamlined, consistent and more in line with Obsidian's design - and I'm excited about its future!! :) Thanks so much for all the hard work on the theme!

**Comment by mbeckrich** [comment]
Thanks! I’m going to have to do a little bit of digging on this one. I need to take a look at how other themes are handling it and see what Obsidian changed. Will update here once it’s fixed!On Dec 19, 2024, at 2:58 AM, Ell ***@***.***> wrote:﻿
This started happening a while back, presumably with an Obsidian update that changed the internal layouting of the settings menu somehow. The disclaimer about using the style settings plugin is now very squished and extends far beyond the bounds of the actual setting:
image.png (view on web)
I'm really loving the development version of the theme - it feels a lot more streamlined, consistent and more in line with Obsidian's design - and I'm excited about its future!! :) Thanks so much for all the hard work on the theme!

**Comment by mbeckrich** [comment]
Okay, this should be fixed on the development branch in the most recent pushes. Let me know if the issue persists!

**Comment by Ellpeck** [comment]
That fixed it, thanks so much!! ❤️
