### ISSUE TITLE
Folder icons don't display

### ISSUE THREAD

**Issue by parthshahp** [catppuccin/obsidian#12]
Folder icons don't display in the file explorer. 
![image](https://user-images.githubusercontent.com/48393781/164781537-aba25dac-4812-467d-928e-79366b54050c.png)

**Comment by mbeckrich** [comment]
These currently don't exist w/in the theme, but will plan to add in a future release. Thanks!

**Comment by parthshahp** [comment]
Oh I see, I was just confused by the picture in the README. Great theme by the way!

**Comment by mbeckrich** [comment]
> Oh I see, I was just confused by the picture in the README. Great theme by the way!

Oh you know what... you're right. :) I must have broken them and then totally forgotten. Will try to get a fix out this weekend.

**Comment by mbeckrich** [comment]
Okay, fixed as of https://github.com/catppuccin/obsidian/commit/813f8854de2c4ebd685fa0947dec88ef1833090a. The icons should now appear if you update the theme.

Thank you for letting me know!
