### ISSUE TITLE
Horizontal bars and table borders not visible.

### ISSUE THREAD

**Issue by KaosBunny** [catppuccin/obsidian#13]
As said in the title, the horizontal bar (`***`) and table borders aren't visible/are barely visible when in preview mode. I've provided an example image.

Not really much more to say.

EndeavourOS + KDE with Obsidian installed through pacman.

[Image](https://i.imgur.com/5B58KEw.png)

**Comment by mbeckrich** [comment]
Gotcha, will fix. Thanks for the example image.
