### ISSUE TITLE
docs: Macchiato file is misspelled, resulting in no image in README.

### ISSUE THREAD

**Issue by isabelincorp** [catppuccin/obsidian#21]
[link referenced in the readme ](https://raw.githubusercontent.com/catppuccin/obsidian/main/assets/raw-flavor-screenshots/macchiato.webp) (spelled correctly) image in the repo, [actual image](https://raw.githubusercontent.com/catppuccin/obsidian/main/assets/raw-flavor-screenshots/macciato.webp) (spelled as "macciato")

**Comment by zarazhas** [comment]
Oops meant to spell "typo"

**Comment by mbeckrich** [comment]
Fixed in https://github.com/catppuccin/obsidian/commit/600bfa107a453f7e1a4b6eef07ba2e7b1a6f0335.
