### ISSUE TITLE
Broken text color

### ISSUE THREAD

**Issue by opakholis** [catppuccin/obsidian#25]
Hi, did I miss something? I'm sure both Obsidian and the Catppuccin theme have the latest version installed, but it looks like the text color is exactly the same as the background.

![image](https://user-images.githubusercontent.com/49778014/197092149-7cea5414-3233-474d-a875-ac335f92af02.png)
![image](https://user-images.githubusercontent.com/49778014/197093628-2240b02f-d3d8-48ea-aafe-4f8bcdc6f5db.png)
![image](https://user-images.githubusercontent.com/49778014/197093666-2b0cee06-abcb-425c-812b-74b210f1df02.png)

**Comment by mbeckrich** [comment]
Odd. I’ve an idea of what it might be, though. Will try to get a fix out in a few minutes!On Oct 20, 2022, at 8:03 PM, Opa Kholis Majid ***@***.***> wrote:﻿
Hi, did I miss something? I'm sure both Obsidian and the Catppuccin theme have the latest version installed, but it looks like the text color is exactly the same as the background.

**Comment by mbeckrich** [comment]
Fixed in https://github.com/catppuccin/obsidian/commit/e5a78e91778aa5756ed833fc04f969a2d2905977. Looks like when I was copying css out of the app css I didn't get the entire length of a set of selectors and ended up styling a little too much text. Let me know if you run into any further issues.

**Comment by opakholis** [comment]
This is what I expected, thanks!🥂
