### ISSUE TITLE
how to set folder colorful ?? 

### ISSUE THREAD

**Issue by nevertoday** [catppuccin/obsidian#28]
thks

**Comment by AnubisNekhet** [comment]
What do you mean by colorful?

**Comment by nevertoday** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/166048/200180266-8bc2a4ac-1239-4e33-b2b1-10817ff6826b.png">

some thing like thi

**Comment by AnubisNekhet** [comment]
Um that seems like the job for a custom snippet, you could probably use css to achieve that.

**Comment by nevertoday** [comment]
so one tell me he use theme named "AnuPpuccin" achieve this effect, but I did not get the theme.

**Comment by mbeckrich** [comment]
> so one tell me he use theme named "AnuPpuccin" achieve this effect, but I did not get the theme.

That is a theme @AnubisNekhet had/has, so they may be able to provide you with a working snippet, but it's a feature that is not part of this version of Catppuccin. You can also try using something like this https://github.com/Lisandra-dev/Obsidian-Snippet-collection/blob/main/F%20-%20Color.css along with the Style Settings plugin.
