### ISSUE TITLE
Highlights are illegible in reading mode

### ISSUE THREAD

**Issue by adrianord** [catppuccin/obsidian#31]
When making a highlight in Editing using `==highlighted text here==` the text looks fine
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3665200/201263966-ce98a722-2411-48bd-85d2-3af772b231ac.png">
When switching into Reading mode, the text becomes illegible 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/3665200/201264119-380fef9f-ea84-46c0-8bf5-279ef5a8302d.png">

This is using the default settings in Style Settings with a new vault

**Comment by mbeckrich** [comment]
Thanks, will fix and review reading mode css in general!On Nov 10, 2022, at 9:37 PM, Adrian Ordonez ***@***.***> wrote:﻿
When making a highlight in Editing using ==highlighted text here== the text looks fine

When switching into Reading mode, the text becomes illegible

This is using the default settings in Style Settings with a new vault

**Comment by mbeckrich** [comment]
Should be fixed in the latest update. Let me know if you run into any issues, though. Thanks for your patience.

**Comment by adrianord** [comment]
Seems it didn't update automatically since the version in the manifest didn't change, but after uninstalling and re-installing it's working great, thanks!

**Comment by mbeckrich** [comment]
Thanks for catching that. Was a late night and I forgot. 🥱 On Nov 11, 2022, at 12:16 PM, Adrian Ordonez ***@***.***> wrote:﻿
Seems it didn't update automatically since the version in the manifest didn't change, but after uninstalling and re-installing it's working great, thanks!
