### ISSUE TITLE
Tags are broken in pop-out windows

### ISSUE THREAD

**Issue by BionicBison05** [catppuccin/obsidian#35]
If a note has been opened in a new window separate from the main window, tags are oversized. This does not affect the default theme.

<img width="1356" alt="Example of issue" src="https://user-images.githubusercontent.com/93722725/210414864-a3f03da4-4848-4c3a-9fa4-0c28928ef148.png">

**Comment by mbeckrich** [comment]
Yup, that looks too big to me also... Should be fixed in https://github.com/catppuccin/obsidian/commit/d972dda3ed297a56f74fd4a135f3d511cc858867! Reopen if you run into further issues after updating.
