### ISSUE TITLE
Search results readability

### ISSUE THREAD

**Issue by ArtemisFowl-san** [catppuccin/obsidian#36]
Hey, there

I really adore the theme you have given us. 

One thing I do find myself struggling with is readability of search results when using the theme in dark mode, as seen in the screenshot. 

![image](https://user-images.githubusercontent.com/72747914/212149873-7970d2a8-6c54-478f-ad14-bff214687fa2.png)

Is there a way to adjust this in style settings or is there another fix for this. I checked the closed issues and could not find anything on this. 

EDIT:
Another example are the folders in the plug in the [another quick switcher plug in](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher). I understand that you cannot have support for all plug ins just thought I would mention it as another example
![image](https://user-images.githubusercontent.com/72747914/212151381-3000d60c-bcd9-4674-83f3-b1f353f4d968.png)

**Comment by mbeckrich** [comment]
Thanks! Getting the search result highlights nailed down has been tricky -- lots of sneaky CSS for them. Can you give me a little more context for the first screenshot? Is it from a plugin as well and are you using the full palette or one of the style settings specific ones? This is what my search results look like:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/88514414/212182690-48a111c0-5451-444e-a0fc-83795d6c1484.png">


I will install the plugin in the second pic and get that fixed.

**Comment by ArtemisFowl-san** [comment]
Hey, thanks for the quick fix for the folder search results, they look perfect now 👍 

As for the first screenshot, it is the same [anotherquickswitcher](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher) plug in and it is the same search bar, only that it already previews some of the search results for headers or keywords or inside the file

This image is the same, so the folder indicator on the right is perfect now as is the file name, only the in-file search results are still very hard to read. 
![image](https://user-images.githubusercontent.com/72747914/212285080-bea189c6-ec95-4440-8a04-9af126ed4ce3.png)

I hope this helps. If I can do anything else to help just let me know.

**Comment by mbeckrich** [comment]
Cool, I think I may have been able to correct it using the grep search feature to test. This should reflect the native search results of the app now. Can you let me know if I am still missing any of the plugin's css? Thanks!
<img width="494" alt="Screenshot 2023-01-13 at 2 13 33 PM" src="https://user-images.githubusercontent.com/88514414/212420253-9b163d02-ff61-4269-9a99-e553aa5fe4ad.png">

**Comment by ArtemisFowl-san** [comment]
Looks perfect now, thanks a lot !
![image](https://user-images.githubusercontent.com/72747914/212466237-a23553aa-b356-442c-b9b3-cd76c32faed1.png)

I don't want to bother you too much with plug in compatbility, because I imagine it is an endless task, but would you mind also looking into the [omnisearch plug in](https://github.com/scambier/obsidian-omnisearch) search results (see screenshot). 

Feel free to skip this if it's too much just thought that I would ask :)

![image](https://user-images.githubusercontent.com/72747914/212466513-6f5b0cb2-29f4-4a95-9e13-4de60e2d95df.png)

**Comment by mbeckrich** [comment]
Glad it’s looking better! I’ll take a look at the other plugin tonight and give you an update when I get it compatible with the theme. :)

**Comment by mbeckrich** [comment]
Okie doke, let me know how that looks now. Don't feel bad about asking for plugin additions -- happy to do it when I have time. You're also welcome to submit PRs for review if you're famliar with CSS and want to contribute. :)

**Comment by ArtemisFowl-san** [comment]
thanks, and yes once I am done with exams for this semester I was thinking about diving a bit deepter into CSS, so will definitely come back to this then :)

**Comment by mbeckrich** [comment]
Great! I updated the readme a couple days ago with some additional info about contributing and there's a footnote that gives an example of how to build the app scss with sass if you haven't used it before. I'll close this for now but let me know if there's anything else I can do to help. Good luck with exams!
