### ISSUE TITLE
Using different theme sub options (latte, frappe, mocha)

### ISSUE THREAD

**Issue by pitoniak32** [catppuccin/obsidian#37]
I am not sure how to go about selecting which version of Catppuccin is selected once it is set as my theme in Obsidian, I tried checking out the CSS snippets linked in the README, and the obsidian docs about CSS snippets.

Would it be possible to show an example of switching the default from `mocha` to `frappe`?

Apologies, I am very new to obsidian

**Comment by pitoniak32** [comment]
I found the answer in the readme after all I am going to open a PR to add more context for new obsidians users that are not aware of community plugins 👍🏼

**Comment by mbeckrich** [comment]
Hey! Sure thing. I have a meeting coming up in 20 minutes, so if this isn't detailed enough, please let me know. :)

1) Obsidian settings page -> Community plugins tab
1a) Disable "Restricted mode" if it is enabled
2) Community plugins section -> "Browse" -> search "Style Settings" -> select "Style Settings" by mgmeyers and install this plugin
3) Return to the initial Community plugins page and, under "Installed plugins" enable "Style Settings" (if it is not already)
4) There should now be a new item called "Style Settings" in the left sidebar of your settings page:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/88514414/217080607-86305f9c-0da5-4b87-9645-5b1e3df0a194.png">
4.continued) Select the aforementioned tab and pick and choose the settings you prefer for Catppuccin. 

Please let me know if you need any additional clarification, help, or run into problems!

**Comment by mbeckrich** [comment]
> I found the answer in the readme after all I am going to open a PR to add more context for new obsidians users that are not aware of community plugins 👍🏼

Perfect, appreciate it :) You can refer to my initial answer if it helps you provide any additional context.

**Comment by pitoniak32** [comment]
That provides the perfect amount of context! Thank you for the quick response! I was going to open a PR with the following lines added to the `# Usage` section, I forgot I wouldn't have access to the repo though, but I think that this extra detail could be helpful for new users

```
To install this plugin you will need to open obsidian and in `Preferences`, under the OPTIONS section, select `Community plugins` and check that `Restricted Mode` is off. Now you can browse for the [Style Settings](https://github.com/mgmeyers/obsidian-style-settings#obsidian-style-settings-plugin) Plugin.

Once you have the plugin installed you should be able to see a heading entry in `Preferences` on the left for `COMMUNITY PLUGINS`, you can now select `Style Settings` and configure your Catppuccin flavor :)

```

**Comment by mbeckrich** [comment]
> That provides the perfect amount of context! Thank you for the quick response! I was going to open a PR with the following lines added to the `# Usage` section, I forgot I wouldn't have access to the repo though, but I think that this extra detail could be helpful for new users
> 
> ```
> To install this plugin you will need to open obsidian and in `Preferences`, under the OPTIONS section, select `Community plugins` and check that `Restricted Mode` is off. Now you can browse for the [Style Settings](https://github.com/mgmeyers/obsidian-style-settings#obsidian-style-settings-plugin) Plugin.
> 
> Once you have the plugin installed you should be able to see a heading entry in `Preferences` on the left for `COMMUNITY PLUGINS`, you can now select `Style Settings` and configure your Catppuccin flavor :)
> ```

You're totally right. I'll throw that in there, thank you! I will add it manually in a few minutes, but if you want to contribute in the future, you should be able to. Check out the Github docs on PRs here https://docs.github.com/en/pull-requests/collaborating-with-pull-requests and this blog post that explains it with some real examples here https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/ if you haven't

**Comment by pitoniak32** [comment]
> 
I will check those out! I have been looking to get into Open Source contributions, I really appreciate all the hard work that goes into keeping these projects going, and would like to give back.

**Comment by pitoniak32** [comment]
Hopefully I am not too late! I have opened a PR with the fork-branch method :)
https://github.com/catppuccin/obsidian/pull/38

**Comment by mbeckrich** [comment]
> Hopefully I am not too late! I have opened a PR with the fork-branch method :)
> #38

Oh no, we just missed each other haha. I will get your section in so you show up on the contributors list. Gimme a sec! And thank you for the kind words.

If you want to review the CONTRIBUTING.md file in the repo, you can see how the (or, my) development process for the theme works and use it as a starting point if you want to add to the theme at all. Otherwise, jump in the Catppuccin discord if you haven't already. Most people I've encountered there are pretty chill and you can ping me in the Obsidian channel if you want to chat about anything. I'm by no means a professional but I'm happy to help however I can.

**Comment by pitoniak32** [comment]
Thank you for all the pointers and help, It is very much appreciated, I will hop on the discord :)

**Comment by mbeckrich** [comment]
Thanks so much for your PR. You are officially are contributor! https://github.com/catppuccin/obsidian/graphs/contributors
