### ISSUE TITLE
Problems with core plugin "backlinks"

### ISSUE THREAD

**Issue by JustAsteri** [catppuccin/obsidian#40]
Text is not shown in the "backlinks" or "linked sections" section at the bottom of the page.

## No mouse hovering
![SCR-20230502-naea](https://user-images.githubusercontent.com/83469583/235781024-fd8473ef-854e-413f-8367-b49864e17252.png)

---

## Mouse hovering
![SCR-20230502-nagk](https://user-images.githubusercontent.com/83469583/235781020-3aded54a-71e4-4378-80d5-558fd4355998.png)

**Comment by mbeckrich** [comment]
Thanks for catching this. I'll try to take a look tonight and get a fix out. Sorry for the headache!

**Comment by mbeckrich** [comment]
This should be fixed in the most recent update. Please reopen the issue if it still happens in edge cases. Thanks!
