### ISSUE TITLE
Text color for currently open bookmarked file it black

### ISSUE THREAD

**Issue by kerbless** [catppuccin/obsidian#41]
See:
![image](https://github.com/catppuccin/obsidian/assets/32358946/6705b405-6b2b-4922-853e-f0bb600e3a2c)
![image](https://github.com/catppuccin/obsidian/assets/32358946/53cd9954-d905-4677-bca4-7df9dccdab09)

**Comment by kerbless** [comment]
Maybe we could make it appear the same as in the files tab, see:
![image](https://github.com/catppuccin/obsidian/assets/32358946/a80db5b4-04b3-4d54-98f6-a6554b05ab24)

**Comment by mbeckrich** [comment]
Thanks, will fix today. Didn’t get a chance to check out the new bookmark stuff during beta! On May 11, 2023, at 4:36 AM, kerbless ***@***.***> wrote:﻿
See:

**Comment by kerbless** [comment]
Hi @mbeckrich, I noticed that something a lot similar happens when moving the bookmark:

https://github.com/catppuccin/obsidian/assets/32358946/82eb9df1-c8a8-4e5c-9346-5e9d5c368447

Should I make a new issue?

**Comment by mbeckrich** [comment]
No need, thanks for bringing this one to my attention too. I’ll get right on it!On May 19, 2023, at 10:45 AM, kerbless ***@***.***> wrote:﻿
Hi @mbeckrich, I noticed that something a lot similar happens when moving the bookmark:
https://github.com/catppuccin/obsidian/assets/32358946/82eb9df1-c8a8-4e5c-9346-5e9d5c368447
Should I make a new issue?

**Comment by mbeckrich** [comment]
Okay @kerbless, the update should fix this. The horizontal line that appears when you drag is `.drop-indicator.is-active`. I don't love how it looks, but I tried a few colors on it and none of them seemed to make it look much better. So if you have any ideas there, let me know and I'm happy to implement it. 

Thanks for your patience and let me know if you run into further issues!

**Comment by kerbless** [comment]
Thanks a lot!
The line now appears doubled but it might have something to do with the new update which overhauled the tree components (see #42)
![image](https://github.com/catppuccin/obsidian/assets/32358946/dfdd9ab8-54e6-4e1b-9c47-584f00550914)
