### ISSUE TITLE
Tree components overhaul in v1.3 broke some stuff

### ISSUE THREAD

**Issue by kerbless** [catppuccin/obsidian#42]
Notice the color and the spacing in these examples
![image](https://github.com/catppuccin/obsidian/assets/32358946/5b099b1f-136a-4086-b37a-99d393f2da24)
![image](https://github.com/catppuccin/obsidian/assets/32358946/dcc7cf80-7d31-407d-b3fd-e70f66708d34)

**Comment by mbeckrich** [comment]
Thanks for the heads up. I tested the beta ahead of the most recent release and thought I had gotten things working with the new tree in my last update, but I guess not completely. 😔 I’ll take another pass today and reply when fixed!On May 26, 2023, at 5:37 AM, kerbless ***@***.***> wrote:﻿
Notice the color and the spacing in these examples

**Comment by mbeckrich** [comment]
Closing this one for now, but if you're still having this issue toss me a reply or reopen. Thanks! <3
