### ISSUE TITLE
catppuccin color palette mismatch

### ISSUE THREAD

**Issue by portus-zephyr** [catppuccin/obsidian#45]
Hi,

There seems to be a mismatch between the colors used [here](https://github.com/catppuccin/obsidian/blob/main/scss/base/_ctp-style-settings.scss) and the colors used in the [catppuccin repo](https://github.com/catppuccin/catppuccin). For example:

**latte**
| color | catppuccin | here |
| - | - | - |
| rosewater |220, 138, 120 | [222, 149, 132](https://github.com/catppuccin/obsidian/blob/4d548e44d1e9362abc139cfe8990b1a0e9223dc9/scss/base/_ctp-style-settings.scss#LL774C20-L774C33) |
| pink | 234, 118, 203 | 236, 131, 208 | 
| yellow | 223, 142, 29 | 228, 147, 32 |
| blue | 30, 102, 245 | 42, 110, 245 |

Is this intended?

**Comment by mbeckrich** [comment]
Good catch. Let me investigate. Someone else generated the variables for the theme, but the official palette itself may have also had some minor tweaks I didn’t know about. I’ll update you when it’s fixed. Thanks!On Jun 22, 2023, at 10:34 AM, Ian ***@***.***> wrote:﻿
Hi,
There seems to be a mismatch between the colors used here and the colors used in the catppuccin repo. For example:
latte



color
catppuccin
here




rosewater
220, 138, 120
222, 149, 132


pink
234, 118, 203
236, 131, 208


yellow
223, 142, 29
228, 147, 32



Is this intended?

**Comment by mbeckrich** [comment]
This should be corrected in the most recent update. Thanks again for letting me know about this -- I have some theories as to how it came to be this way, but my guess is the specific reasoning is lost to Discord. If you catch anything other misapplied colors, feel free to reopen.
