### ISSUE TITLE
Low contrast for file name popup when moving files

### ISSUE THREAD

**Issue by OwOSwordsman** [catppuccin/obsidian#49]
The file name text is difficult to read while using the latte theme variant. 

https://github.com/catppuccin/obsidian/assets/29553973/3bef1774-8e63-489b-a85c-5888dc82cdaf

No issues with the mocha theme variant.

https://github.com/catppuccin/obsidian/assets/29553973/94f44ea2-ff10-4d8f-8d75-7d7adb7d4d73

I am on MacOS 12.6.8 with Obsidian Version 1.3.7 (Installer 1.1.9), and I am using the latest version 0.4.16 of the Catppuccin theme.

**Comment by mbeckrich** [comment]
Good catch, I’ll get you a fix soon. Thanks!On Aug 14, 2023, at 12:35 PM, OwO Swordsman ***@***.***> wrote:﻿
The file name text is difficult to read while using the latte theme variant.
https://github.com/catppuccin/obsidian/assets/29553973/3bef1774-8e63-489b-a85c-5888dc82cdaf
No issues with the mocha theme variant.
https://github.com/catppuccin/obsidian/assets/29553973/94f44ea2-ff10-4d8f-8d75-7d7adb7d4d73
I am on MacOS 12.6.8 with Obsidian Version 1.3.7 (Installer 1.1.9), and I am using the latest version 0.4.16 of the Catppuccin theme.

**Comment by mbeckrich** [comment]
This should be fixed in the most recent update. Let me know if you run into further issues. I noticed that there are some other tweaks I will need to make specific to the light theme, so I will work on those as I have time.

**Comment by OwOSwordsman** [comment]
Yep it's fixed. Thank you for getting it fixed so quickly!
