### ISSUE TITLE
Latte flavor is not selectable

### ISSUE THREAD

**Issue by mainrs** [catppuccin/obsidian#53]
I just installed the plugin as described in the README. The latte flavor is missing though...

![image](https://github.com/catppuccin/obsidian/assets/5113257/5fc825d2-d0d1-4458-98c5-699c42bd52e5)

**Comment by justTOBBI** [comment]
As stated in the option, this is the dark mode option you are currently selecting.
Select Latte in the `Light Theme` Setting

**Comment by mainrs** [comment]
I changed my base theme from dark to light too now. In case this triggers conditional options to appear. 
But I cannot find the light theme setting in the styling plugin.

![image](https://github.com/catppuccin/obsidian/assets/5113257/573d32d8-d899-4a01-9768-3bf17d78acb2)

Searching for dark gives me back the dropdown I've uploaded above in my initial issue description.
