### ISSUE TITLE
Tag visibility

### ISSUE THREAD

**Issue by qdgiang** [catppuccin/obsidian#56]
Hey there,
In other themes, there's one thing that I really like, which is the way the tag is differentiated from normal text. Take this pill from anuppuccin for example:
![anu](https://github.com/catppuccin/obsidian/assets/55189671/9ef97024-dde1-410c-8920-29dbac302f1c)
Is it possible for you to implement something like that? Current tag in catppuccin looks the same as normal text so it bothers me a little bit.
![cat](https://github.com/catppuccin/obsidian/assets/55189671/f8446411-a919-486a-bbee-99c51454b725)
Love your theme btw. Ty for your effort!

**Comment by mbeckrich** [comment]
Thanks, I understand your preference here. It’s something I can add to Style Settings, and then you can control color/size of tag pills. Currently, it’s similar to Bear, where the tags are designed to flow more with text, but I know that’s not how everyone uses them! So I’ll add this to Style Settings when I get some time. Thanks for your thoughts. 😊 On Feb 2, 2024, at 7:42 AM, Giang ***@***.***> wrote:﻿
Hey there,
In other themes, there's one thing that I really like, which is the way the tag is differentiated from normal text. Take this pill from anuppuccin for example:
anu.png (view on web)
Is it possible for you to implement something like that? Current tag in catppuccin looks the same as normal text so it bothers me a little bit.
cat.png (view on web)
Love your theme btw. Ty for your effort!

**Comment by greed-d** [comment]
Is this still not resolved?

**Comment by mbeckrich** [comment]
This has been implemented in a recent push. Please reopen if you run into any issues. Thanks for the suggestion!

<img width="793" alt="Screenshot 2024-09-20 at 3 19 29 PM" src="https://github.com/user-attachments/assets/f3d51c36-4e16-4a57-ac4b-8370738c7453">
<img width="783" alt="Screenshot 2024-09-20 at 3 19 39 PM" src="https://github.com/user-attachments/assets/9fb86133-de6e-44b6-88d7-96c8b2c2648b">
