### ISSUE TITLE
Strikethrough on links does not render correctly

### ISSUE THREAD

**Issue by tgrosinger** [catppuccin/obsidian#64]
Please see the demo video:

https://github.com/catppuccin/obsidian/assets/597386/9ffdc725-2005-40e1-b444-034887e09656

**Comment by mbeckrich** [comment]
Thanks! Will take a look. On Jun 9, 2024, at 10:28 AM, Tony Grosinger ***@***.***> wrote:﻿
Please see the demo video:
https://github.com/catppuccin/obsidian/assets/597386/9ffdc725-2005-40e1-b444-034887e09656

**Comment by mbeckrich** [comment]
Okay, this is the behavior of the default theme:

![image](https://github.com/catppuccin/obsidian/assets/88514414/dd2c7730-4fc0-4c99-b92f-4946a6a6631a)

This is how it should now look in Catppuccin:

![image](https://github.com/catppuccin/obsidian/assets/88514414/e7f6b1c5-c913-45dc-b329-159c13c095a6)

Please reopen if the issue remains or something else pops up.
