### ISSUE TITLE
Low unselected text visibility when creating a new folder

### ISSUE THREAD

**Issue by arthur-st** [catppuccin/obsidian#65]
![4GyH7rI](https://github.com/catppuccin/obsidian/assets/29796606/bbb9f5a5-5d4d-4191-8c51-6434efe22296)

**Comment by mbeckrich** [comment]
Thanks! Will fix. On Jun 23, 2024, at 4:20 PM, Arthur Stramkals ***@***.***> wrote: 4GyH7rI.png (view on web) — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

**Comment by lowrank** [comment]
My solution is to install ``Style Settings`` plugin, then in the options of that plugin, you can change the color of file name, the default is ``white``, you may change to ``accent``.

**Comment by mbeckrich** [comment]
This should be fixed in the most recent push. Please let reopen if you run into further issues. Thank you for offering helpful advice, too, @lowrank!
