### ISSUE TITLE
No font style colors in blockquotes

### ISSUE THREAD

**Issue by Aidavdw** [catppuccin/obsidian#66]
I have set a custom colour for bold text in the Style Settings.
The colour is applied in display mode in free-standing text as well as callouts, but the default blockquote color remains in blockquotes. 
The following markdown
```
In normal text, the colour is **preserved**.
>[!example]
> Callouts **do** get coloured

>In blockquotes however, **colour is not set**
```
 renders as
![image](https://github.com/user-attachments/assets/9d4e167c-856e-43e2-88a7-066a920b155f)
In source mode, the colour is also not applied, but that is alright I suppose.

**Comment by mbeckrich** [comment]
Thanks for the suggested fix! I’ll take a look today and get this straightened out. On Jul 16, 2024, at 6:59 AM, Aidavdw ***@***.***> wrote:﻿
It appears that the color is only set for the --bold-color.
strong,
.cm-strong {
    --bold-color: rgb(var(--ctp-bold, var(--ctp-sapphire)));
}
With the following extra selectors, and using the standard color tag, I got it to work.
strong,
.cm-strong,
.cm-s-obsidian span.cm-formatting-strong,
.cm-s-obsidian span.cm-strong {
    --bold-color: rgb(var(--ctp-bold, var(--ctp-sapphire)));
    color: rgb(var(--ctp-bold, var(--ctp-sapphire)));
}
Not super familiar with how you have your scss setup, but maybe this is an okay way to do it?

**Comment by mbeckrich** [comment]
Okie doke, reviewed and used your code in https://github.com/catppuccin/obsidian/commit/11d610f1949c0c6fb458494a69e901a0ce49e263. You should be credited on the commit and in the readme now. Thanks for your contribution!

**Comment by Aidavdw** [comment]
cheers, thanks for the quick reply!
