### ISSUE TITLE
Folder note name goes invisble when selected

### ISSUE THREAD

**Issue by ThomasCarey4** [catppuccin/obsidian#67]
![image](https://github.com/user-attachments/assets/564fe3b8-245e-4473-9f13-dbac7b43cec8)

and when hovered over:

![image](https://github.com/user-attachments/assets/404f1f01-c7ca-4876-8880-9f81aff3d364)

This is with no other extensions other than [Folder Notes](https://github.com/LostPaul/obsidian-folder-notes)

**Comment by mbeckrich** [comment]
Thanks, will investigate!On Sep 29, 2024, at 3:50 PM, Thomas Carey ***@***.***> wrote:﻿
image.png (view on web)
and when hovered over:
image.png (view on web)
This is with no other extensions other than Folder Notes

**Comment by mbeckrich** [comment]
Background colors should now show properly when using the Folder Notes plugin. Please reopen if additional work is needed!
