### ISSUE TITLE
Poor visibility on mentions header upon hovering when collapsed

### ISSUE THREAD

**Issue by lokesh-krishna** [catppuccin/obsidian#74]
This is what the mentions header looks like when hovered upon in its collapsed state:

![grim-2024-11-13-22-32-16](https://github.com/user-attachments/assets/0abb409c-48c1-498c-b85b-0883d46edf24)

This is fine when hovering upon them in their expanded states:

![image](https://github.com/user-attachments/assets/3f99df1a-83df-49ba-b007-feaef318ab86)

**Comment by mbeckrich** [comment]
Thanks! Will take a look this afternoon.

**Comment by mbeckrich** [comment]
This should be fixed in the most recent update. Thanks for bringing it to my attention!
