### ISSUE TITLE
quick font size adjustment not working

### ISSUE THREAD

**Issue by dubbyvee** [catppuccin/obsidian#8]
this might be a compatibility issue. the ctrl + zoom is not working when changing font size inside a note. ctrl + and ctrl - are working but it is intended for the interface zoom.

**Comment by mbeckrich** [comment]
> this might be a compatibility issue. the ctrl + zoom is not working when changing font size inside a note. ctrl + and ctrl - are working but it is intended for the interface zoom.

Is this occurring when you use other themes or no theme, too? I am noticing what you describe seems to occur regardless of theme choice, but I might be misunderstanding the problem.
