### ISSUE TITLE
No window controls

### ISSUE THREAD

**Issue by Frai7ty** [catppuccin/obsidian#9]
No titlebar controls.
Currently on Windows.
![image](https://user-images.githubusercontent.com/3834210/160504974-790bdeec-1406-446f-98c0-e3e330c2b47c.png)

**Comment by mbeckrich** [comment]
Thank you for catching this. I do not use Obsidian on my Windows machine and didn't think to test there. If you go ahead and update the theme, the buttons should now be visible post-@[a95f159](https://github.com/catppuccin/obsidian/commit/a95f159638388c3a411a7eeb1d08c24c566b94f0). I'll see if I have some time this week to make them look a little nicer, but at least you can look at them now. :) Let me know if you notice anything else and hf with Stellaris, good game.
