### ISSUE TITLE
Alternate checkboxes

### ISSUE THREAD

**Issue by Irubataru** [catppuccin/obsidian#91]
First of all, thank you for making this theme! <3

One thing I really miss though from the [minimal theme](https://minimal.guide) is [_Alternate Checkboxes_](https://minimal.guide/checklists). Is there any way something like these could be implemented in the Catppuccin theme? It's a shame these have to be implemented theme by theme.

![image](https://github.com/user-attachments/assets/9d313462-6477-4eba-bcd9-ecddbef62bb9)

**Comment by mbeckrich** [comment]
Thanks! And thanks for the suggestion. Let me look into this further and I’ll get back to you with an update. On Nov 18, 2024, at 12:47 AM, Aleksandra Glesaaen Ødegård ***@***.***> wrote:﻿
First of all, thank you for making this theme! <3
One thing I really miss though from the minimal theme is Alternate Checkboxes. Is there any way something like these could be implemented in the Catppuccin theme? It's a shame these have to be implemented theme by theme.
image.png (view on web)

**Comment by garbosz** [comment]
+1 on this the theme is really nice but i also really like the extra functionality from more checkbox options.

**Comment by mbeckrich** [comment]
On it! I’ve had some irl work come up but I’ll try to get this implemented sometime over the next few days. On Nov 22, 2024, at 6:15 PM, Garbosz ***@***.***> wrote:﻿
+1 on this the theme is really nice but i also really like the extra functionality from more checkbox options.

**Comment by mbeckrich** [comment]
This should be implemented in #94. If some functionality from Minimal is missing, please reopen let me know. And thank you to Kepano for his hard work in the community. <3
